from setuptools import setup, find_packages
import os

setup(
    name="POSEIDON",
    version="1.4.0",
    description="Exoplanet atmospheric retrieval package",
    long_description=open(os.path.join(os.path.dirname(__file__), "README.rst")).read(),
    long_description_content_type="text/x-rst",
    author="Ryan J. MacDonald",
    author_email="ryanjmac@umich.edu",
    license="BSD 3-Clause License",
    packages=["POSEIDON"],
    include_package_data=True,
    python_requires="<3.13",
    install_requires=[
        "numpy<2",
        "scipy",
        "matplotlib",
        "astropy",
        "h5py",
        "numba",
        "pandas",
        "tqdm",
        "mpi4py",
        "pysynphot",
        "pymultinest",
        "spectres",
        "jupyter",
        "scikit-learn",
        "pytest",
        "cmasher",
        "batman-package",
        "scikit-learn",
        "miepython==2.5.5",
        "setuptools==81.0.0",
    ],
    zip_safe=False,
)
