name: POSEIDON CI Pytest testing

on:
  push:
    branches:    
      - 'main'
      - 'documentation_update'
  pull_request:
    branches:    
      - 'main'
      - 'documentation_update'

jobs:
  test:
    name: Test on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Anaconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        channels: conda-forge, defaults
        use-only-tar-bz2: true
        auto-update-conda: true
        auto-activate-base: true
    - name: Create conda environment
      run: |
        echo "begin: PATH=$PATH;"
        conda create --name test_install python=3.9 -y
        conda activate test_install || true
    - name: Install mpi4py
      run: |
        conda install -c conda-forge mpi4py -y
    - name: Install pymultinest
      run: |
        conda install -c conda-forge pymultinest -y
    - name: Install package
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    - name: Run tests
      run: |
        pytest