name: Pytest testing

on:
  push:
    branches:    
      - 'main'
      - 'dev'
      - 'python_3.11_support'
  pull_request:
    branches:
      - 'main'
      - 'dev'
      - 'python_3.11_support'

jobs:
  test:
    name: Test on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.9', '3.10', '3.11'] 
    steps:
    - uses: actions/checkout@v4

    - name: Free disk space
      run: |
        sudo swapoff -a
        sudo rm -f /swapfile
        sudo apt clean
        docker rmi $(docker image ls -aq)
        df -h

    - name: Set up Anaconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniconda-version: "latest"
        channels: conda-forge, defaults
        use-only-tar-bz2: true
        auto-update-conda: true
        auto-activate-base: true

    - name: Create conda environment on Ubuntu
      if: runner.os == 'Linux'
      run: |
        echo "begin: PATH=$PATH;" 
        conda create --name test_install python=${{ matrix.python-version }} -y

    - name: Create conda environment on MacOS
      if: runner.os == 'macOS'
      run: |
        echo "begin: PATH=$PATH;" 
        CONDA_SUBDIR=osx-64 conda create --name test_install python=${{ matrix.python-version }} -y

    - name: Install mpi4py and pymultinest on Ubuntu
      if: runner.os == 'Linux'
      run: |
        conda activate test_install || true
        conda install -c conda-forge mpi4py -y
        conda install -c conda-forge pymultinest -y

    - name: Install mpi4py and pymultinest on MacOS
      if: runner.os == 'macOS'
      run: |
        conda activate test_install || true
        conda env config vars set CONDA_SUBDIR=osx-64
        conda install -c conda-forge mpi4py -y
        conda install -c conda-forge pymultinest -y

    - name: Install POSEIDON
      run: |
        conda activate test_install || true
        pip install -e .

    - name: Download input files (only CIA opacity for CI tests)
      if: steps.restore_cache.outputs.cache-hit != 'true'
      run: |
        mkdir -p inputs/opacity
        mkdir -p inputs/chemistry_grids
        wget --wait=1 --random-wait --continue --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1VxIhlVwOelix4BOZxa7oieV5hbP4Q8Bx' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1VxIhlVwOelix4BOZxa7oieV5hbP4Q8Bx" -O inputs/opacity/Opacity_database_cia.hdf5 && rm -rf /tmp/cookies.txt
        wget --wait=1 --random-wait --continue --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1ar1u7yMnMvWAp6bLc2kENg2b4khxdww3' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1ar1u7yMnMvWAp6bLc2kENg2b4khxdww3" -O inputs/chemistry_grids/fastchem_database.hdf5 && rm -rf /tmp/cookies.txt

    - name: Set environment variables
      run: |
        echo "POSEIDON_input_data=$GITHUB_WORKSPACE/inputs/" >> $GITHUB_ENV
        echo "PYSYN_CDBS=$GITHUB_WORKSPACE/inputs/stellar_grids/" >> $GITHUB_ENV

    - name: Run tests
      run: |
        conda activate test_install || true
        pytest -rA
