name: POSEIDON CI Pytest testing

on:
  push:
    branches:    
      - 'main'
      - 'documentation_update'
  pull_request:
    branches:    
      - 'main'
      - 'documentation_update'

jobs:
  test:
    name: Test on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Anaconda
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Add conda to PATH
      run: |
        echo 'export PATH=${{ steps.setup-python.outputs.home }}/bin:$PATH' >> $GITHUB_ENV
    - name: Install pymultinest
      run: |
        conda install -c conda-forge mpi4py pymultinest -y
    - name: Install package
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    - name: Run tests
      run: |
        pytest