name: POSEIDON CI Pytest testing

on:
  push:
    branches:    
      - 'main'
      - 'documentation_update'
  pull_request:
    branches:    
      - 'main'
      - 'documentation_update'

jobs:
  test:
    name: Test on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9] 
    steps:
    - uses: actions/checkout@v3
    - name: free disk space
      run: |
        sudo swapoff -a
        sudo rm -f /swapfile
        sudo apt clean
        docker rmi $(docker image ls -aq)
        df -h
    - name: Set up Anaconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        channels: conda-forge, defaults
        use-only-tar-bz2: true
        auto-update-conda: true
        auto-activate-base: true
    - name: Create conda environment
      run: |
        echo "begin: PATH=$PATH;"
        conda create --name test_install python=${{ matrix.python-version }} -y
    - name: Install mpi4py and pymultinest
      run: |
        conda activate test_install || true
        conda install -c conda-forge mpi4py -y
        conda install -c conda-forge pymultinest -y
    - name: Install POSEIDON
      run: |
        conda activate test_install || true
        python -m pip install --upgrade pip
        pip install -e .
    - name: Download input files
      run: |
        mkdir -p inputs/opacity
        conda activate test_install || true
        pip install zenodo_get
        zenodo_get --file stellar_grids.zip 7500292 -O inputs/stellar_grids.zip
        zenodo_get --file Opacity_database_0.01cm-1_Temperate.hdf5 7500292 -O inputs/opacity/Opacity_database_0.01cm-1_Temperate.hdf5
        zenodo_get --file Opacity_database_cia.hdf5 7500292 -O inputs/opacity/Opacity_database_cia.hdf5
        zenodo_get --file Opacity_database_0.01cm-1.hdf5 7500292 -O inputs/opacity/Opacity_database_0.01cm-1.hdf5
    - name: Extract input files
      run: |
        unzip inputs/stellar_grids.zip -d inputs
    - name: Set environment variables
      run: |
        echo 'export POSEIDON_input_data=inputs/opacity' >> $GITHUB_ENV
        echo 'export PYSYN_CDBS=inputs/stellar_grids' >> $GITHUB_ENV
    - name: Run tests
      run: |
        conda activate test_install || true
        pytest